services:
  - type: web
    name: azulucrm
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RENDER_DISK_PATH
        value: /var/data
      - key: PORT
        value: 8000
    disk:
      name: azulu-data
      mountPath: /var/data
      sizeGB: 1 