"""bring schema up to date with models

Revision ID: 5e555d80e983
Revises: 826f60946d68
Create Date: 2025-09-30 10:10:15.395519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e555d80e983'
down_revision: Union[str, Sequence[str], None] = '826f60946d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('string_collection', app.models.JSONList(), nullable=True),
    sa.Column('big_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_key'), 'contents', ['key'], unique=True)
    op.create_table('dj_socials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('tiktok', sa.String(), nullable=True),
    sa.Column('spotify', sa.String(), nullable=True),
    sa.Column('soundcloud', sa.String(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.Column('apple_music', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dj_socials_id'), 'dj_socials', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('time_zone', sa.String(length=255), nullable=True),
    sa.Column('ticket_status', sa.String(length=255), nullable=True),
    sa.Column('ticket_link', sa.String(length=255), nullable=True),
    sa.Column('lineup', app.models.JSONList(), nullable=True),
    sa.Column('genres', app.models.JSONList(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_table('mailing_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailing_list_email'), 'mailing_list', ['email'], unique=True)
    op.create_index(op.f('ix_mailing_list_id'), 'mailing_list', ['id'], unique=False)
    op.create_table('djs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('social_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['social_id'], ['dj_socials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_djs_id'), 'djs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_djs_id'), table_name='djs')
    op.drop_table('djs')
    op.drop_index(op.f('ix_mailing_list_id'), table_name='mailing_list')
    op.drop_index(op.f('ix_mailing_list_email'), table_name='mailing_list')
    op.drop_table('mailing_list')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_dj_socials_id'), table_name='dj_socials')
    op.drop_table('dj_socials')
    op.drop_index(op.f('ix_contents_key'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###
